env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 8:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Targeted resolution coupled AMIP long runs"

    steps:

      # # coupler only
      - label: "MPI AMIP FINE: target longrun no topo no ice"
        key: "amip_longrun_target_spunup"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name amip_longrun_target_spunup_offline_noice_notopo --coupled true --start_date 19790101 --monthly_checkpoint true --surface_setup PrescribedSurface --dt_cpl 200 --energy_check false --mode_name amip --mono_surface false --vert_diff true --moist equil --rad clearsky --precip_model 0M --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 4e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 200secs --t_end 400days --job_id amip_longrun_target_spunup_offline_noice_notopo --dt_save_to_sol 1000days --dt_save_to_disk 10days --apply_limiter false --FLOAT_TYPE Float64 --post_process false"
        artifact_paths: "experiments/AMIP/modular/output/amip/amip_longrun_target_spunup_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          RUN_NAME: "n64_amip_noice_notopo_noedmf_spinup"
          NEW_RESTART_DIR: "/groups/esm/lenka/couplerdel/ClimaCoupler.jl/experiments/AMIP/modular/output/amip/amip_restart_from_notopo-noice_artifacts/edmf_cache_hack/"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 64
          slurm_mem: 0GB

      # # coupler only
      - label: "MPI AMIP FINE: target longrun no ice, earth topo"
        key: "amip_longrun_target_spunup_n64_noice_topo_spinup"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name amip_longrun_target_spunup_n64_offline_noice_topo --coupled true --start_date 19790101 --monthly_checkpoint true --surface_setup PrescribedSurface --dt_cpl 100 --energy_check false --mode_name amip --mono_surface false --vert_diff true --moist equil --rad clearsky --precip_model 0M --topography Earth --topo_smoothing true --use_reference_state false --z_elem 35 --dz_bottom 50 --h_elem 12 --kappa_4 4e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --dt 100secs --t_end 100days --job_id amip_longrun_target_spunup_n64_offline_noice_topo --dt_save_to_sol 1000days --dt_save_to_disk 10days --apply_limiter false --FLOAT_TYPE Float64  --post_process false"
        artifact_paths: "experiments/AMIP/modular/output/amip/amip_longrun_target_spunup_n64_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          RESTART_T: 18316800
          RUN_NAME: "n64_amip_noice_topo_noedmf_spinup"
          NEW_RESTART_DIR: "/groups/esm/lenka/couplerdel/ClimaCoupler.jl/experiments/AMIP/modular/output/amip/amip_restart_from_topo-noice_artifacts/edmf_cache_hack/"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 0GB
