name = "ClimaCoupler"
uuid = "4ade58fe-a8da-486c-bd89-46df092ec0c7"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.1.0"

[deps]
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
ClimaCore = "0.10"
DocStringExtensions = "0.9"
PrettyTables = "1.3"
