name = "ClimaCoupler"
uuid = "4ade58fe-a8da-486c-bd89-46df092ec0c7"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.1.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
