agents:
  queue: new-central
  slurm_time: 24:00:00
  modules: climacommon/2024_03_18

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1

  CONFIG_PATH: "config/longrun_configs"
  PERF_CONFIG_PATH: "config/perf_configs"

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

      - echo "--- Instantiate perf env"
      - "julia --project=perf/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

    concurrency: 1
    concurrency_group: 'depot/climacoupler-longruns'

  - wait

  - group: "Current target tests: AMIP surface"

    steps:

      - label: "MPI AMIP FINE: new target amip: topo + 1M"
        key: "amip_target_topo_1M"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target_topo_1M.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_target_topo_1M_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G
