agents:
  queue: new-central
  slurm_time: 24:00:00
  modules: climacommon/2024_03_18

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1

  CONFIG_PATH: "config/longrun_configs"
  PERF_CONFIG_PATH: "config/perf_configs"

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

      - echo "--- Instantiate perf env"
      - "julia --project=perf/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  # DYAMOND AMIP: 1 day (convection resolving)
  - label: "GPU AMIP SUPERFINE: dyamond_target"
    key: "gpu_dyamond_target"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

      - "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/gpu_dyamond_target.yml"
    artifact_paths: "experiments/AMIP/output/amip/gpu_dyamond_target_artifacts/*"
    agents:
      queue: clima
      slurm_mem: 20GB
      slurm_gpus: 1
      modules: common

  - wait

  - group: "Coupler integration and conservation tests"

    steps:

      # Integration tests - the expected results were also confirmed locally
      - label: "Slabplanet_aqua: nocouple"
        key: "slabplanet_aqua_atmos_sf_nocouple" # SF at each Atmos stage, no coupling, prescribed SST from atmos
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_atmos_sf_nocouple.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_atmos_sf_nocouple_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "Slabplanet_aqua: couple"
        key: "slabplanet_aqua_atmos_sf_couple" # SF at each Atmos stage, coupling, prescribed SST from coupler - identical results to the above confirm 1) initial conditions in Atmos are unchanged compared to the slab, 2) coupling not introducing variability when constant surface
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_atmos_sf_couple.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_atmos_sf_couple_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "Slabplanet_aqua: coupler fluxes"
        key: "slabplanet_aqua_coupler_sf" # SF at each coupler timestep, constant ocean - comparing to the above runs, this tests the sensitivity of less frequent flux calculation
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_coupler_sf.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_coupler_sf_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "Slabplanet_aqua: coupler fluxes, evolving ocean"
        key: "slabplanet_aqua_coupler_sf_evolve_ocn" # SF at each coupler timestep, evolving ocean - comparing to the above run, tests the sensitivity of evolving ocean
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_coupler_sf_evolve_ocn.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_coupler_sf_evolve_ocn_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "Slabplanet_terra: coupler fluxes, evolving bucket"
        key: "slabplanet_terra" # SF at each coupler timestep, evolving ocean - comparing to the above run, tests the sensitivity of evolving bucket
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_terra.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_terra/slabplanet_terra_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "Slabplanet: coupler fluxes, evolving ocean and land"
        key: "slabplanet_coupler_sf_evolve_ocn"
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_coupler_sf_evolve_ocn.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

  - group: "Current target tests: idealized surface"

    steps:

      - label: "ClimaAtmos standalone target"
        command:
          - srun julia --project=experiments/AMIP/ test/component_model_tests/climaatmos_standalone/atmos_driver.jl --config_file test/component_model_tests/climaatmos_standalone/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean.yml
        artifact_paths: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean/*"
        env:
          BUILD_HISTORY_HANDLE: ""
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "TARGET IDEALIZED: new target aqua - fixed ocean T, nocouple, atmos flux calc"
        key: "slabplanet_aqua_target_nocouple"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_target_nocouple.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_target_nocouple_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "TARGET IDEALIZED: new target aqua - fixed ocean T, coupler flux calc"
        key: "slabplanet_aqua_target"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_target.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_target_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "TARGET IDEALIZED: new target aqua - evolving slab ocean T"
        key: "slabplanet_aqua_target_evolve_ocn"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_aqua_target_evolve_ocn.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet_aqua/slabplanet_aqua_target_evolve_ocn_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "TARGET IDEALIZED: new target slab - fixed ocean T, bucket"
        key: "slabplanet_target"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_target.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet/slabplanet_target_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "TARGET IDEALIZED: new target slab - evolving slab ocean T, bucket"
        key: "slabplanet_target_evolve_ocn"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/slabplanet_target_evolve_ocn.yml"
        artifact_paths: "experiments/AMIP/output/slabplanet/slabplanet_target_evolve_ocn_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G


  - group: "Current target tests: AMIP surface"

    steps:

      - label: "MPI AMIP FINE: new target amip"
        key: "amip_target"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_target_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: new target amip: topo"
        key: "amip_target_topo"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target_topo.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_target_topo_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: new target amip: topo + diagedmf"
        key: "amip_target_topo_diagedmf"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target_topo_diagedmf.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_target_topo_diagedmf_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 20G

  - group: "Current target tests on GPU: AMIP surface"

    steps:

      - label: "GPU AMIP FINE: new target amip: topo"
        key: "gpu_amip_target_topo"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/gpu_amip_target_topo.yml"
        artifact_paths: "experiments/AMIP/output/amip/gpu_amip_target_topo_artifacts/*"
        agents:
          slurm_gpus: 1
          slurm_mem: 16GB

      - label: "GPU AMIP FINE: new target amip: topo + diagedmf"
        key: "gpu_amip_target_topo_diagedmf"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/gpu_amip_target_topo_diagedmf.yml"
        artifact_paths: "experiments/AMIP/output/amip/gpu_amip_target_topo_diagedmf_artifacts/*"
        agents:
          slurm_gpus: 1
          slurm_mem: 16GB

  - group: "Other AMIP targets"

    steps:

      # DYAMOND AMIP: 1 day (convection resolving)
      - label: "MPI AMIP SUPERFINE: dyamond_target"
        key: "dyamond_target"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/dyamond_target.yml"
        artifact_paths: "experiments/AMIP/output/amip/dyamond_target_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      # mid-resolution AMIP: MPI performance scaling (10 days)
      - label: "MPI AMIP FINE: n64"
        key: "mpi_amip_fine_n64"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_n64_shortrun.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_n64_shortrun_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: n32"
        key: "mpi_amip_fine_n32"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_n32_shortrun.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_n32_shortrun_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 8
          slurm_nodes: 4
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: n8"
        key: "mpi_amip_fine_n8"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_n8_shortrun.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_n8_shortrun_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 8
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: n2" # 10d take 21h, so reducing to 1d
        key: "mpi_amip_fine_n2"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_n2_shortrun.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_n2_shortrun_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 2
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: n1" # also reported by longruns with a flame graph; 10d take 21h, so reducing to 1d
        key: "mpi_amip_fine_n1"
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_n1_shortrun.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_n1_shortrun_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - label: "MPI AMIP FINE: n1 no couple" # sim time = Δt_cpl (~ benchmarking with standalone models)
        key: "mpi_amip_fine_n1_nocouple"
        command: "julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_n1_shortrun_nocouple.yml"
        artifact_paths: "experiments/AMIP/output/amip/amip_n1_shortrun_nocouple_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      # mpi_amip_fine_n1 flame graph report (NB: arguments passed from the ci pipeline.yml)
      - label: ":rocket: performance: flame graph diff: perf_target_amip_n1_shortrun"
        command: "julia --color=yes --project=perf perf/flame_diff.jl --config_file $PERF_CONFIG_PATH/perf_diff_target_amip_n1_shortrun.yml"
        artifact_paths: "perf/output/perf_diff_target_amip_n1_shortrun/*"
        agents:
          slurm_ntasks_per_node: 1
          slurm_nodes: 1
          slurm_mem_per_cpu: 16G

      - wait

      # plot job performance history
      - label: ":chart_with_downwards_trend: build history"
        command:
          - build_history main # name of branch to plot
        artifact_paths:
          - "build_history.html"

      - wait

      - label: ":envelope: Slack report: build_history"
        command:
          - slack-upload -c "#coupler-report" -f build_history.html -m html -n build_history -x "Overall job performance"

      - label: ":envelope: Slack report: Slabplanet"
        command:
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_energy_log_bucket.png -m png -n slab_coarse_log -x "Slabplanet energy conservation (log error)"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_energy_bucket.png -m png -n slab_coarse -x "Slabplanet energy conservation"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_water_log_bucket.png -m png -n slab_coarse_w_log -x "Slabplanet water conservation (log error)"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_water_bucket.png -m png -n slab_coarse_w -x "Slabplanet water conservation"

      - label: ":envelope: Slack report: target AMIP"
        command:
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/amip/amip_target_artifacts/amip_paperplots.png -m png -n amip_fine -x "AMIP Target Longrun"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/amip/amip_target_artifacts/biases.png -m png -n amip_fine -x "AMIP Target Longrun"

      - label: ":envelope: Slack report: Flame Diff"
        command:
          - slack-upload -c "#coupler-report" -f perf/output/perf_diff_target_amip_n1_shortrun/flame_diff.html -m png -n amip_fine_flamegraphdiff -x "AMIP Longrun FlameGraphDiff"
          - slack-upload -c "#coupler-report" -f perf/output/perf_diff_target_amip_n1_shortrun/flame_diff_self_count.html -m png -n amip_fine_flamegraphdiffself -x "AMIP Longrun FlameGraphDiffSelf"
