env:
  JULIA_VERSION: "1.8.2"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/moist_mpi_earth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/moist_mpi_earth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/moist_mpi_earth/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Targeted resolution coupled AMIP long runs"

    steps:

      - label: "Moist earth with slab surface - notmono + modular: bulk gray no_sponge idealinsol freq_dt_cpl"
        key: "modular_slabplanet"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver_modular.jl --run_name default_modular --enable_threading true --coupled true --surface_scheme bulk  --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface false --h_elem 4 --precip_model 0M"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/default_modular_artifacts/total_energy*.png"
        env:
          FLAME_PLOT: ""
        agents:
          slurm_ntasks: 1
          slurm_mem_per_cpu: 16G

      - label: "AMIP"
        key: "mpi_amip_fine_long"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --run_name target_amip_n32_longrun --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad allskywithclear --z_elem 50 --dz_top 3000 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --dt_cpl 150 --dt 150secs --dt_rad 1hours --idealized_insolation false --FLOAT_TYPE Float64 --energy_check false --mode_name amip --t_end 5days --dt_save_to_sol 10days --mono_surface false --precip_model 0M"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/amip/target_amip_n32_longrun_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 16G

      - label: "AMIP: perf"
        key: "mpi_amip_fine"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --run_name target_amip_n1_shortrun --enable_threading false --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad allskywithclear --z_elem 50 --dz_top 3000 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --dt_cpl 150 --dt 150secs --dt_rad 1hours --idealized_insolation false --FLOAT_TYPE Float64 --energy_check false --mode_name amip --t_end 0.5days --dt_save_to_sol 10days --mono_surface false --precip_model 0M"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/amip/target_amip_n1_shortrun_artifacts/*"
        env:
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_mem_per_cpu: 16G

      - wait

      # plot job performance history
      - label: ":chart_with_downwards_trend: build history"
        command:
          - build_history staging # name of branch to plot
        artifact_paths:
          - "build_history.html"

      - wait

      - label: ":rocket: performance: flame graph diff: perf_target_amip_n1_shortrun"
        key: "flame_graph_diff"
        command: "julia --color=yes --project=perf perf/flame_diff.jl --run_name 4"
        artifact_paths: "perf/output/perf_diff_target_amip_n1_shortrun/*"
        agents:
          slurm_mem: 20GB
        env:
          BUILD_HISTORY_HANDLE: ""

      - wait

      - label: ":envelope: Slack report: build_history"
        command:
          - slack-upload -c "#coupler-reports" -f build_history.html -m html -n build_history -x "Overall job performance"

      - label: ":envelope: Slack report: Slabplanet"
        command:
          - slack-upload -c "#coupler-reports" -f experiments/AMIP/moist_mpi_earth/output/slabplanet/default_modular_artifacts/total_energy_log_bucket.png -m png -n slab_coarse -x "Slabplanet conservation"

      - label: ":envelope: Slack report: target AMIP"
        command:
          - slack-upload -c "#coupler-reports" -f experiments/AMIP/moist_mpi_earth/output/amip/target_amip_n32_longrun_artifacts/amip_paperplots.png -m png -n amip_fine -x "AMIP Longrun"

      - label: ":envelope: Slack report: Flame Diff"
        command:
          - slack-upload -c "#coupler-reports" -f perf/output/perf_diff_target_amip_n1_shortrun/flame_diff.html -m png -n amip_fine_flamegraphdiff -x "AMIP Longrun FlameGraphDiff"
          - slack-upload -c "#coupler-reports" -f perf/output/perf_diff_target_amip_n1_shortrun/flame_diff_self_count.html -m png -n amip_fine_flamegraphdiffself -x "AMIP Longrun FlameGraphSelf"