agents:
  queue: central
  slurm_time: 24:00:00
  modules: julia/1.9.3 cuda/12.2 ucx/1.14.1_cuda-12.2 openmpi/4.1.5_cuda-12.2 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100

  CONFIG_PATH: "config/longrun_configs"
  PERF_CONFIG_PATH: "config/perf_configs"

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

      - echo "--- Instantiate perf env"
      - "julia --project=perf/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Longrun SF sensitivity tests"

    steps:
      
      - label: "AMIP Businger"
        key: "amip_Businger_long"
        command: "srun julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --config_file $CONFIG_PATH/amip_businger.yml"
        artifact_paths: "experiments/AMIP/modular/output/amip/interactive_debug_run_Businger_long_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 8
          slurm_mem: 20GB
      
      - label: "AMIP Holtslag"
        key: "amip_Holtslag_long"
        command: "srun julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --config_file $CONFIG_PATH/amip_holtslag.yml"
        artifact_paths: "experiments/AMIP/modular/output/amip/interactive_debug_run_Holtslag_long_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 8
          slurm_mem: 20GB
      
      - label: "AMIP Beljaars"
        key: "amip_Beljaars_long"
        command: "srun julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --config_file $CONFIG_PATH/amip_beljaars.yml"
        artifact_paths: "experiments/AMIP/modular/output/amip/interactive_debug_run_Beljaars_long_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 8
          slurm_mem: 20GB
      
      - label: "AMIP Cheng"
        key: "amip_Cheng_long"
        command: "srun julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --config_file $CONFIG_PATH/amip_cheng.yml"
        artifact_paths: "experiments/AMIP/modular/output/amip/interactive_debug_run_Cheng_long_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 8
          slurm_mem: 20GB
      
      - label: "AMIP Grachev"
        key: "amip_Grachev_long"
        command: "srun julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --config_file $CONFIG_PATH/amip_grachev.yml"
        artifact_paths: "experiments/AMIP/modular/output/amip/interactive_debug_run_Grachev_long_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 8
          slurm_mem: 20GB
      
      - label: "AMIP Gryanik"
        key: "amip_Gryanik_long"
        command: "srun julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --config_file $CONFIG_PATH/amip_gryanik.yml"
        artifact_paths: "experiments/AMIP/modular/output/amip/interactive_debug_run_Gryanik_long_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 8
          slurm_mem: 20GB
