agents:
  queue: new-central
  slurm_time: 24:00:00
  modules: climacommon/2024_02_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1

  CONFIG_PATH: "config/longrun_configs"
  PERF_CONFIG_PATH: "config/perf_configs"

timeout_in_minutes: 1440

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

      - echo "--- Instantiate perf env"
      - "julia --project=perf/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Current target tests: AMIP surface"

    steps:

      - label: "MPI AMIP FINE: new target amip: topo + diagedmf"
        key: "amip_target_topo_diagedmf"
        command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target_topo_diagedmf.yml "
        artifact_paths: "experiments/AMIP/output/amip/amip_target_topo_diagedmf_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks_per_node: 16
          slurm_nodes: 4
          slurm_mem_per_cpu: 20G
        
      # - label: "MPI AMIP FINE: new target amip: topo + diagedmf"
      #   key: "amip_target_topo_diagedmf2"
      #   command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target_topo_diagedmf2.yml"
      #   artifact_paths: "experiments/AMIP/output/amip/amip_target_topo_diagedmf2_artifacts/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #     BUILD_HISTORY_HANDLE: ""
      #   agents:
      #     slurm_ntasks_per_node: 16
      #     slurm_nodes: 4
      #     slurm_mem_per_cpu: 20G
      
      # - label: "MPI AMIP FINE: new target amip: topo + diagedmf"
      #   key: "amip_target_topo_diagedmf3"
      #   command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/amip_target_topo_diagedmf3.yml"
      #   artifact_paths: "experiments/AMIP/output/amip/amip_target_topo_diagedmf3_artifacts/*"
      #   env:
      #     CLIMACORE_DISTRIBUTED: "MPI"
      #     BUILD_HISTORY_HANDLE: ""
      #   agents:
      #     slurm_ntasks_per_node: 16
      #     slurm_nodes: 4
      #     slurm_mem_per_cpu: 20G

      - wait

      # plot job performance history
      - label: ":chart_with_downwards_trend: build history"
        command:
          - build_history main # name of branch to plot
        artifact_paths:
          - "build_history.html"

      - wait

      - label: ":envelope: Slack report: build_history"
        command:
          - slack-upload -c "#coupler-report" -f build_history.html -m html -n build_history -x "Overall job performance"

      - label: ":envelope: Slack report: Slabplanet"
        command:
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_energy_log_bucket.png -m png -n slab_coarse_log -x "Slabplanet energy conservation (log error)"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_energy_bucket.png -m png -n slab_coarse -x "Slabplanet energy conservation"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_water_log_bucket.png -m png -n slab_coarse_w_log -x "Slabplanet water conservation (log error)"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/slabplanet/slabplanet_coupler_sf_evolve_ocn_artifacts/total_water_bucket.png -m png -n slab_coarse_w -x "Slabplanet water conservation"

      - label: ":envelope: Slack report: target AMIP"
        command:
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/amip/amip_target_artifacts/amip_paperplots.png -m png -n amip_fine -x "AMIP Target Longrun"
          - slack-upload -c "#coupler-report" -f experiments/AMIP/output/amip/amip_target_artifacts/biases.png -m png -n amip_fine -x "AMIP Target Longrun"

      - label: ":envelope: Slack report: Flame Diff"
        command:
          - slack-upload -c "#coupler-report" -f perf/output/perf_diff_target_amip_n1_shortrun/flame_diff.html -m png -n amip_fine_flamegraphdiff -x "AMIP Longrun FlameGraphDiff"
          - slack-upload -c "#coupler-report" -f perf/output/perf_diff_target_amip_n1_shortrun/flame_diff_self_count.html -m png -n amip_fine_flamegraphdiffself -x "AMIP Longrun FlameGraphDiffSelf"
