run_name: "perf_diff_default_modular_unthreaded"
FLOAT_TYPE: "Float64"
coupled: true
surface_setup: "PrescribedSurface"
moist: "equil"
vert_diff: "true"
rad: "gray"
energy_check: true
mode_name: "slabplanet"
t_end: "10days"
dt_save_to_sol: "9days"
dt_cpl: 200
dt: "200secs"
mono_surface: true
h_elem: 4
precip_model: "0M"
anim: true
apply_limiter: true
job_id: "perf_diff_default_modular_unthreaded"
