monthly_checkpoint: true
moist: "equil"
vert_diff: "true"
rad: "gray"
energy_check: false
mode_name: "amip"
anim: true
t_end: "182days"
dt_save_to_sol: "1days"
dt_cpl: 400
dt: "400secs"
mono_surface: false
h_elem: 6
dt_save_restart: "10days"
precip_model: "0M"
apply_limiter: false
surface_setup: "PrescribedSurface"
run_name: "interactive_debug_run_Businger_long"
job_id: "interactive_debug_run_Businger_long"
monthly_checkpoint: true
universal_function: "Businger"