alpha_rayleigh_uh: 0
alpha_rayleigh_w: 10
apply_limiter: false
dt: "150secs"
dt_cpl: 150
dt_rad: "2days"
dt_save_to_sol: "1days"
dz_bottom: 30
dz_top: 3000
h_elem: 4
job_id: "amip_albedo_static_map"
land_albedo_type: "map_static"
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
run_name: "amip_albedo_static_map"
t_end: "1days"
vert_diff: "true"
z_elem: 50
z_stretch: false
