run_name: "coarse_single_ft64_hourly_checkpoints_co2"
hourly_checkpoint: true
moist: "equil"
vert_diff: "true"
rad: "allskywithclear"
energy_check: false
mode_name: "amip"
anim: true
t_end: "32days"
dt_save_to_sol: "1days"
dt_cpl: 400
dt: "400secs"
mono_surface: false
h_elem: 6
dt_save_restart: "10days"
precip_model: "0M"
apply_limiter: false
job_id: "coarse_single_ft64_hourly_checkpoints_co2"
