run_name: "coarse_single_modular_ft32"
moist: "equil"
vert_diff: "true"
rad: "gray"
energy_check: false
mode_name: "amip"
anim: true
t_end: "10days"
dt_save_to_sol: "100days"
dt_cpl: 200
dt: "200secs"
mono_surface: true
h_elem: 6
dt_save_restart: "10days"
precip_model: "0M"
apply_limiter: false
FLOAT_TYPE: "Float32"
job_id: "coarse_single_modular_ft32"
