FLOAT_TYPE: "Float32"
anim: false
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_allsky_diagedmf_0M.yml"
dt: "100secs"
dt_cloud_fraction: "1hours"
dt_cpl: 100
dt_rad: "2days"
dt_save_state_to_disk: "1days"
dt_save_to_sol: "1days"
energy_check: false
hourly_checkpoint: true
idealized_insolation: false
job_id: "gpu_amip_target_topo_diagedmf_shortrun"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
run_name: "gpu_amip_target_topo_diagedmf_shortrun"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "1days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxes"
use_reference_state: false
