moist: "equil"
vert_diff: "true"
rad: "allskywithclear"
energy_check: true
mode_name: "slabplanet"
t_end: "10days"
dt_save_to_sol: "0.5days"
dt_cpl: 400
dt: "400secs"
mono_surface: true
turb_flux_partition: "CombinedStateFluxes"
h_elem: 4
dt_save_restart: "5days"
precip_model: "0M"
run_name: "interactive_debug_run_bus"
job_id: "interactive_debug_run_bus"
monthly_checkpoint: true
universal_function: "Businger" # "Businger" or "Gryanik"
