anim: true
apply_limiter: false
dt: "400secs"
dt_cpl: 400
dt_save_restart: "10days"
dt_save_to_sol: "1days"
energy_check: false
h_elem: 6
hourly_checkpoint: true
job_id: "try"
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "clearsky"
idealized_insolation: false
run_name: "try"
t_end: "3days"
vert_diff: "true"