run_name: "slabplanet_eisenman"
surface_setup: "PrescribedSurface"
moist: "equil"
vert_diff: "true"
rad: "gray"
energy_check: true
mode_name: "slabplanet_eisenman"
t_end: "2days"
dt_save_to_sol: "9days"
dt_cpl: 200
dt: "200secs"
mono_surface: true
h_elem: 6
precip_model: "0M"
anim: true
apply_limiter: false
job_id: "slabplanet_eisenman"
conservation_softfail: true
