alpha_rayleigh_uh: 0
alpha_rayleigh_w: 10
apply_limiter: false
conservation_softfail: true
dt: "200secs"
dt_cpl: 3600
dt_rad: "6hours"
dt_save_to_sol: "3600secs"
energy_check: true
h_elem: 6
idealized_insolation: false
job_id: "target_params_in_slab_test3"
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "allskywithclear"
rayleigh_sponge: true
run_name: "target_params_in_slab_test3"
t_end: "10days"
vert_diff: "true"
