moist: "equil"
vert_diff: "true"
rad: "allskywithclear"
rayleigh_sponge: true
alpha_rayleigh_uh: 0
alpha_rayleigh_w: 10
energy_check: true
mode_name: "slabplanet"
t_end: "10days"
dt_save_to_sol: "3600secs"
dt_cpl: 3600
dt: "200secs"
dt_rad: "6hours"
idealized_insolation: false
mono_surface: true
h_elem: 6
precip_model: "0M"
run_name: "target_params_in_slab_test2"
apply_limiter: true
job_id: "target_params_in_slab_test2"
