run_name: "target_amip_n1_shortrun"
moist: "equil"
vert_diff: "true"
rad: "gray"
z_elem: 50
dz_top: 3000
dz_bottom: 30
h_elem: 16
kappa_4: 1e16
z_stretch: false
rayleigh_sponge: true
alpha_rayleigh_uh: 0
alpha_rayleigh_w: 10
dt_cpl: 150
dt: "150secs"
dt_rad: "1hours"
energy_check: false
mode_name: "amip"
t_end: "0.01days"
dt_save_to_sol: "1days"
mono_surface: false
precip_model: "0M"
apply_limiter: false
job_id: "target_amip_n1_shortrun"
