run_name: "amip_longrun_target"
anim: true
dt_cpl: 100
energy_check: false
mode_name: "amip"
mono_surface: false
vert_diff: "true"
moist: "equil"
rad: "clearsky"
precip_model: "0M"
z_elem: 35
dz_bottom: 50
h_elem: 12
kappa_4: 3e16
rayleigh_sponge: true
alpha_rayleigh_uh: 0
dt: "100secs"
t_end: "100days" # TODO this has been decreased from 140 days to avoid instability #460
job_id: "amip_longrun_target"
dt_save_to_sol: "5days"
dt_save_to_disk: "5days"
hourly_checkpoint: true
apply_limiter: false
surface_setup: "DefaultMoninObukhov"
land_albedo_type: "function"
start_date: "19790301"
coupler_toml_file: "toml/amip_longrun_target.toml"