run_name: "amip_target"
anim: true
dt_cpl: 150
energy_check: false
mode_name: "amip"
mono_surface: false
dt: "150secs"
t_end: "200days"
job_id: "amip_target"
dt_save_to_sol: "10days"
dt_save_to_disk: "20days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml"
surface_setup: "PrescribedSurface"
land_albedo_type: "map_temporal"
start_date: "19790301"