anim: true
approximate_linear_solve_iters: 2
apply_limiter: false
dt_cloud_fraction: "1hours"
dt_cpl: 100
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
dt: "100secs"
dz_bottom: 30.0
dz_top: 3000.0
energy_check: false
h_elem: 16
implicit_diffusion: true
FLOAT_TYPE: "Float32"
hourly_checkpoint: true
idealized_insolation: false
job_id: "amip_target_topo"
land_albedo_type: "map_temporal"
mode_name: "amip"
moist: "equil"
mono_surface: false
netcdf_interpolate_z_over_msl: true
override_Ï„_precip: false
precip_model: "0M"
rad: "allskywithclear"
rayleigh_sponge: true
run_name: "amip_target_topo"
start_date: "19790828"
surface_setup: "PrescribedSurface"
t_end: "100days"
topo_smoothing: true
topography: "Earth"
coupler_toml_file: [target/amip.toml]
z_elem: 63
z_max: 55000.0
turb_flux_partition: "CombinedStateFluxes"
use_reference_state: false
vert_diff: "true"