alpha_rayleigh_uh: 0
alpha_rayleigh_w: 10
apply_limiter: false
dt: "150secs"
dt_cpl: 86200
dt_rad: "1hours"
dt_save_to_sol: "100days"
dz_bottom: 30
dz_top: 3000
energy_check: false
h_elem: 16
job_id: "amip_n1_shortrun_nocouple"
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
run_name: "amip_n1_shortrun_nocouple"
t_end: "1days"
vert_diff: "true"
z_elem: 50
z_stretch: false
