run_name: "amip_target_topo"
anim: true
dt_cpl: 100
energy_check: false
mode_name: "amip"
mono_surface: false
dt: "100secs"
t_end: "100days"
job_id: "amip_target_topo"
dt_save_to_sol: "10days"
dt_save_state_to_disk: "20days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M.yml"
surface_setup: "PrescribedSurface"
land_albedo_type: "map_temporal"
start_date: "19790301"
topography: "Earth"
topo_smoothing: true
use_reference_state: false
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"