monthly_checkpoint: true
energy_check: false
mode_name: "amip"
anim: true
t_end: "300days"
dt_save_to_sol: "1days"
dt_cpl: 400
mono_surface: false
dt_save_restart: "10days"
surface_setup: "PrescribedSurface"
run_name: "interactive_debug_run_Cheng"
job_id: "interactive_debug_run_Cheng"
monthly_checkpoint: true
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M.yml"
atmos_toml_file: "toml/longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M.toml"
universal_function: "Cheng"
