FLOAT_TYPE: "Float32"
atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
dt: "120secs"
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
energy_check: false
hourly_checkpoint: true
hourly_checkpoint_dt: 720
netcdf_output_at_levels: true
output_default_diagnostics: true
start_date: "20100401"
surface_setup: "PrescribedSurface"
t_end: "10days"
topo_smoothing: true
topography: "Earth"
coupler_toml_file: "toml/amip_target_topo_diagedmf.toml"
turb_flux_partition: "CombinedStateFluxesMOST"
use_reference_state: false
diagnostics:
  - short_name: [rsdt, rsut, rsds, rsus]
    period: 1days
    writer: h5
  - short_name: [rsdt, rsut, rsds, rsus]
    period: 1days
