apply_limiter: false
dt: "150secs"
dt_cpl: 150
dt_rad: "1hours"
dt_save_to_sol: "100days"
dz_bottom: 30
dz_top: 3000
energy_check: false
h_elem: 16
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
t_end: "1days"
vert_diff: "true"
z_elem: 50
z_stretch: false
