FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
anim: true
apply_limiter: false
approximate_linear_solve_iters: 2
coupler_toml_file: "toml/amip_target_topo.toml"
dt: "100secs"
dt_cloud_fraction: "1hours"
dt_cpl: 100
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
dz_bottom: 30.0
dz_top: 3000.0
energy_check: false
h_elem: 16
hourly_checkpoint: true
hyperdiff: "CAM_SE"
implicit_diffusion: true
land_albedo_type: "map_temporal"
mode_name: "amip"
moist: "equil"
mono_surface: false
netcdf_interpolate_z_over_msl: true
ode_algo: "ARS343"
precip_model: "1M"
rad: "allskywithclear"
rayleigh_sponge: true
start_date: "20100101"
smoothing_order: 2
surface_setup: "PrescribedSurface"
t_end: "100days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "FriersonDiffusion"
z_elem: 63
z_max: 55000.0
