FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
anim: true
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.yml"
dt: "100secs"
dt_cloud_fraction: "1hours"
dt_cpl: 100
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
ode_algo: "ARS343"
energy_check: false
hourly_checkpoint: true
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
hyperdiffusion: "CAM_SE"
netcdf_interpolate_z_over_msl: true
rad: "allskywithclear"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "100days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "true"
