run_name: "amip_target_topo_diagedmf"
anim: true
dt_cpl: 100
energy_check: false
mode_name: "amip"
mono_surface: false
dt: "100secs"
t_end: "40days"
job_id: "amip_target_topo_diagedmf"
dt_save_to_sol: "10days"
dt_save_state_to_disk: "20days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_allsky_diagedmf_0M.yml"
surface_setup: "PrescribedSurface"
land_albedo_type: "map_temporal"
start_date: "19790301"
topography: "Earth"
topo_smoothing: true
FLOAT_TYPE: "Float32"
idealized_insolation: false
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
netcdf_output_at_levels: true
