dt: "120secs"
dt_cpl: 120
dt_rad: "1hours"
dz_bottom: 30
dz_top: 3000
energy_check: false
h_elem: 16
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
t_end: "1days"
vert_diff: true
z_max: 55000.0
z_elem: 63
