anim: true
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean.yml"
dt_cloud_fraction: "1hours"
dt_cpl: 100
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
dt: "100secs"
energy_check: false
hourly_checkpoint: true
job_id: "amip_target"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
prognostic_surface: false
rad: "allskywithclear"
run_name: "amip_target"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "200days"
turb_flux_partition: "CombinedStateFluxes"
vert_diff: "true"