run_name: "august"
coupled: true
start_date: "19790301"
monthly_checkpoint: true
surface_setup: "PrescribedSurface"
dt_cpl: 100
energy_check: false
mode_name: "amip"
mono_surface: false
vert_diff: "true"
moist: "equil"
rad: "clearsky"
precip_model: "0M"
z_elem: 35
dz_bottom: 50
h_elem: 12
kappa_4: 4e16
rayleigh_sponge: true
alpha_rayleigh_uh: 0
dt: "100secs"
t_end: "400days"
job_id: "august"
dt_save_to_sol: "10days"
dt_save_to_disk: "1days"
apply_limiter: false
FLOAT_TYPE: "Float64"
post_process: false
anim: true
hourly_checkpoint: true
apply_limiter: false
surface_setup: "PrescribedSurface"
land_albedo_type: "function"
coupler_toml_file: "toml/august.toml"
land_temperature_anomaly: "amip"