FLOAT_TYPE: "Float32"
anim: false
apply_limiter: false
atmos_config_file: "config/gpu_configs/gpu_aquaplanet_diagedmf.yml"
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: 120
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
energy_check: false
hourly_checkpoint: false
idealized_insolation: false
job_id: "gpu_amip_target_topo_diagedmf"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: false
run_name: "gpu_amip_target_topo_diagedmf"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "400days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxes"
use_reference_state: false
