FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
anim: false
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_equil_helem12_allsky_progedmf_0M.yml"
restart_file: ~
dt: "20secs"
dt_cloud_fraction: "1hours"
dt_cpl: 20
dt_rad: "1hours"
dt_save_state_to_disk: "10days"
energy_check: false
hourly_checkpoint: false
idealized_insolation: false
job_id: "gpu_amip_target_topo_progedmf"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: true
rayleigh_sponge: true
run_name: "gpu_amip_target_topo_progedmf"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "30days"
topo_smoothing: true
topography: "Earth"
coupler_toml_file: "toml/amip_target_topo_progedmf.toml"
turb_flux_partition: "CombinedStateFluxes"
use_reference_state: true
