atmos_config_file: "config/longrun_configs/longrun_aquaplanet_dyamond.yml"
dt: "30secs"
dt_cpl: 30
topography: "Earth"
dt_save_state_to_disk: "0.5days"
dt_save_to_sol: "0.5days"
energy_check: false
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
monthly_checkpoint: false
start_date: "20100101"
t_end: "14days"
turb_flux_partition: "CombinedStateFluxesMOST"
prescribe_ozone: true
aerosol_radiation: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr, hfes, edt]
    period: 6hours
