atmos_config_file: "config/longrun_configs/longrun_aquaplanet_dyamond.yml"
dt: "30secs"
dt_cpl: 30
dt_save_state_to_disk: "0.5days"
dt_save_to_sol: "0.5days"
energy_check: false
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
monthly_checkpoint: false
start_date: "20100101"
t_end: "1days"
turb_flux_partition: "CombinedStateFluxesMOST"
