run_name: "new_target"
anim: true
dt_cpl: 150
energy_check: false
mode_name: "amip"
mono_surface: false
vert_diff: "true"
moist: "equil"
rad: "clearsky"
precip_model: "0M"
z_elem: 35
dz_bottom: 50
h_elem: 12
kappa_4: 3e16
rayleigh_sponge: true
alpha_rayleigh_uh: 0
dt: "100secs"
t_end: "200days" # TODO this has been decreased from 140 days to avoid instability #460
job_id: "new_target"
dt_save_to_sol: "5days"
dt_save_to_disk: "1days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml"
atmos_toml_file: "toml/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky.toml"
surface_setup: PrescribedSurface
