run_name: "new_target_nocouple"
anim: true
dt_cpl: 25920000
energy_check: false
mode_name: "amip"
mono_surface: false
t_end: "300days"
job_id: "new_target_nocouple"
dt_save_to_sol: "20days"
dt_save_to_disk: "10days"
dt_save_restart: "5days"
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml"
atmos_toml_file: "toml/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky.toml"
monthly_checkpoint: false
hourly_checkpoint: true
surface_setup: DefaultMoninObukhov
