run_name: "slabplanet_target_evolve_ocn_900"
anim: true
dt_cpl: 150
energy_check: false
mode_name: "slabplanet"
mono_surface: false
dt: "150secs"
t_end: "900days"
job_id: "slabplanet_target_evolve_ocn_900"
dt_save_to_sol: "10days"
dt_save_to_disk: "20days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml"
surface_setup: "PrescribedSurface"
land_albedo_type: "function"
evolving_ocean: true
start_date: "19790301"