anim: true
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M.yml"
dt_cloud_fraction: "1hours"
dt_cpl: 150
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
dt: "150secs"
energy_check: false
evolving_ocean: false
hourly_checkpoint: true
job_id: "slabplanet_target"
land_albedo_type: "function"
mode_name: "slabplanet"
mono_surface: false
run_name: "slabplanet_target"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "200days"
turb_flux_partition: "CombinedStateFluxes"
vert_diff: "true"