run_name: "slabplanet_aqua_coupler_sf"
job_id: "slabplanet_aqua_coupler_sf"
moist: "equil"
vert_diff: "true"
rad: "gray"
precip_model: "0M"
energy_check: true
mode_name: "slabplanet_aqua"
t_end: "20days"
dt_save_to_sol: "10days"
dt_cpl: 400
dt: "400secs"
mono_surface: true
h_elem: 4
anim: true
apply_limiter: false
turb_flux_partition: "CombinedStateFluxes"
surface_setup: "PrescribedSurface"
land_albedo_type: "function"
evolving_ocean: false
start_date: "19790301"