run_name: "slabplanet_aqua_target"
anim: true
dt_cpl: 150
energy_check: false
mode_name: "slabplanet_aqua"
mono_surface: false
dt: "150secs"
t_end: "200days"
job_id: "slabplanet_aqua_target"
dt_save_to_sol: "10days"
dt_save_state_to_disk: "20days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M.yml"
surface_setup: "PrescribedSurface"
land_albedo_type: "function"
evolving_ocean: false
start_date: "19790301"
dt_rad: "1hours"
