run_name: "slabplanet_new_target_evolve_ocn"
anim: true
dt_cpl: 150
energy_check: true
mode_name: "slabplanet"
mono_surface: false
dt: "150secs"
t_end: "200days" # TODO this has been decreased from 140 days to avoid instability #460
job_id: "slabplanet_new_target_evolve_ocn"
dt_save_to_sol: "5days"
dt_save_to_disk: "5days"
apply_limiter: false
hourly_checkpoint: true
turb_flux_partition: "CombinedStateFluxes"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml"
surface_setup: "PrescribedSurface"
land_albedo_type: "function"
evolving_ocean: true
start_date: "19790301"
