run_name: "slabplanet_default_longrun"
moist: "equil"
vert_diff: "true"
rad: "gray"
energy_check: true
mode_name: "slabplanet"
t_end: "60days"
dt_save_to_sol: "10days"
dt_cpl: 200
dt: "200secs"
mono_surface: true
h_elem: 6
precip_model: "0M"
anim: true
apply_limiter: false
job_id: "slabplanet_default_longrun"
