anim: true
apply_limiter: false
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "10days"
energy_check: true
evolving_ocean: true
h_elem: 6
land_albedo_type: "function"
mode_name: "slabplanet_aqua"
moist: "equil"
ode_algo: "ARS343"
mono_surface: true
precip_model: "0M"
rad: "gray"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "20days"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "true"
