anim: true
apply_limiter: false
conservation_softfail: true
dt: "200secs"
dt_cpl: 1728000
dt_save_to_sol: "10days"
energy_check: true
evolving_ocean: false
h_elem: 6
land_albedo_type: "function"
mode_name: "slabplanet_aqua"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
run_name: "slabplanet_aqua_atmos_sf_nocouple"
start_date: "19790301"
surface_setup: "DefaultMoninObukhov"
t_end: "20days"
turb_flux_partition: "CombinedStateFluxes"
vert_diff: "true"
