anim: true
apply_limiter: false
conservation_softfail: true
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "10days"
energy_check: true
h_elem: 4
job_id: "slabplanet_terra"
land_albedo_type: "function"
mode_name: "slabplanet_terra"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
run_name: "slabplanet_terra"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "20days"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "true"
