run_name: "slabplanet_aqua_atmos_sf_couple"
job_id: "slabplanet_aqua_atmos_sf_couple"
moist: "equil"
vert_diff: "true"
rad: "gray"
precip_model: "0M"
energy_check: true
mode_name: "slabplanet_aqua"
t_end: "20days"
dt_save_to_sol: "10days"
dt_cpl: 200
dt: "200secs"
mono_surface: true
h_elem: 6
anim: true
apply_limiter: false
turb_flux_partition: "CombinedStateFluxes"
surface_setup: "DefaultMoninObukhov"
land_albedo_type: "function"
evolving_ocean: false
start_date: "19790301"