anim: true
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M.yml"
dt: "150secs"
dt_cloud_fraction: "1hours"
dt_cpl: 150
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
energy_check: false
evolving_ocean: true
hourly_checkpoint: true
job_id: "slabplanet_target_evolve_ocn"
land_albedo_type: "function"
mode_name: "slabplanet"
mono_surface: false
run_name: "slabplanet_target_evolve_ocn"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "100days"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "true"
