anim: true
apply_limiter: false
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_0M.yml"
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: 120
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
dt_save_to_sol: "10days"
energy_check: false
evolving_ocean: true
hourly_checkpoint: true
land_albedo_type: "function"
mode_name: "slabplanet_aqua"
mono_surface: false
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "120days"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "true"
