FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_dyamond.yml"
cloud_model: "quadrature"
coupler_toml_file: "toml/amip.toml"
dt: "60secs"
dt_cpl: "60secs"
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
dz_bottom: 30.0
energy_check: false
h_elem: 60
hourly_checkpoint: true
hourly_checkpoint_dt: 720
initial_condition: "artifact\"DYAMOND_SUMMER_ICS_p98deg\"/DYAMOND_SUMMER_ICS_p98deg.nc"
land_albedo_type: "map_temporal"
land_initial_condition: "experiments/ClimaEarth/input/bucket_ic_august.nc"
mode_name: "amip"
mono_surface: false
netcdf_interpolation_num_points: [720, 360, 63]
netcdf_output_at_levels: true
output_default_diagnostics: true
radiation_reset_rng_seed: true
rayleigh_sponge: true
start_date: "20100801"
surface_setup: "PrescribedSurface"
t_end: "10days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
viscous_sponge: true
z_elem: 63
z_max: 60000.0
extra_atmos_diagnostics:
  - short_name: [ts, ta, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hfes, evspsbl, pr]
    period: "1days"
