FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
cloud_model: quadrature
coupler_toml_file: "toml/amip.toml"
dt: "120secs"
dt_cpl: 120
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
dz_bottom: 100.0
energy_check: false
h_elem: 16
hourly_checkpoint: true
hourly_checkpoint_dt: 720
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
#netcdf_interpolation_num_points: [90, 45, 31]
netcdf_output_at_levels: true
output_default_diagnostics: true
radiation_reset_rng_seed: true
rayleigh_sponge: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "32days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
turbconv: ~
vert_diff: "FriersonDiffusion"
viscous_sponge: true
z_elem: 39
z_max: 60000.0
