FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
anim: false
#atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_0M_earth.yml"
coupler_toml_file: "toml/amip.toml"
dt: "180secs"
dt_cpl: 180
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
dz_bottom: 100.0
energy_check: false
h_elem: 8
hourly_checkpoint: true
hourly_checkpoint_dt: 720
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_interpolation_num_points: [90, 45, 31]
netcdf_output_at_levels: true
output_default_diagnostics: true
rayleigh_sponge: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "549days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
viscous_sponge: false
z_elem: 31
z_max: 50000.0
#diagnostics:
#  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr, edt, hfes]
#    period: 30mins
