env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      # - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate package env"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate sea breeze env"
      - "julia --project=experiments/ClimaCore/sea_breeze -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaCore/sea_breeze -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaCore/sea_breeze -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate amip modular"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/modular/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf env"
      - "julia --project=perf/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test env"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Unit Tests"
    steps:
      - label: "MPI Regridder unit tests"
        key: "regridder_mpi_tests"
        command: "mpiexec julia --color=yes --project=test/ test/mpi_tests/regridder_mpi_tests.jl --run_name regridder_mpi --job_id regridder_mpi"
        timeout_in_minutes: 5
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          config: cpu
          queue: central
          slurm_nodes: 3
          slurm_tasks_per_node: 1

      - label: "MPI BCReader unit tests"
        key: "bcreader_mpi_tests"
        command: "mpiexec julia --color=yes --project=test/ test/mpi_tests/bcreader_mpi_tests.jl --run_name bcreader_mpi --job_id bcreader_mpi"
        timeout_in_minutes: 20
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          config: cpu
          queue: central
          slurm_nodes: 3
          slurm_tasks_per_node: 1

      - label: "Perf flame graph diff tests"
        command: "julia --color=yes --project=perf/ perf/flame_test.jl --run_name flame_test --job_id flame_perf_target"
        timeout_in_minutes: 5
        agents:
          config: cpu
          queue: central
          slurm_nodes: 3
          slurm_tasks_per_node: 1

      - label: "Component model tests"
        command: "julia --color=yes --project=test/ test/component_model_tests.jl  --run_name component_test --job_id component_test"
        timeout_in_minutes: 5

  - group: "Integration Tests"
    steps:

      # Drivers for release >


      # SLABPLANET

      # Slabplanet default:
      # - this is the most lightweight example with conservation and visual checks, with CLI specification as follows
      #   - numerics: dt = dt_cpl = 200s, nelem = 4
      #   - physics: bulk aerodynamic surface fluxes, gray radiation, idealized insolation, equil moisture model, 0-moment microphysics
      #   - input data: monotonous remapping (land mask, SST, SIC)
      #   - slurm: unthreaded, 1 ntask
      #   - diagnostics: check and plot energy conservation, output plots after 9 days
      - label: "Slabplanet: default"
        key: "slabplanet_default"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name slabplanet_default --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface  --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 9days --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 4 --precip_model 0M --anim true --job_id slabplanet_default"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/slabplanet_default_artifacts/*"

      # Test: non-monotonous remapping for land mask
      - label: "Slabplanet: non-monotonous surface remap"
        key: "slabplanet_non-monotonous"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name slabplanet_nonmono --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface  --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 9days --dt_cpl 200 --dt 200secs --mono_surface false --h_elem 4 --precip_model 0M --anim true --job_id slabplanet_nonmono"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/slabplanet_nonmono_artifacts/*"
        agents:
          slurm_mem: 20GB


      # AMIP

      # ...


      # PERFORMANCE

      # slabplanet default: track unthreaded performance (alloc tests, flame graph, flame graph diff, build history)
      - label: ":rocket: Slabplanet: default (unthreaded)"
        key: "modular_slabplanet_unthreaded"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name default_modular_unthreaded --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface  --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 9days --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 4 --precip_model 0M --anim true --job_id default_modular_unthreaded"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/default_modular_unthreaded_artifacts/*"
        env:
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: ":rocket: Slabplanet: default (unthreaded) - flame graph and allocation tests"
        command: "julia --color=yes --project=perf perf/flame.jl --run_name 1 --job_id perf_default_modular_unthreaded"
        artifact_paths: "perf/output/perf_default_modular_unthreaded/*"
        agents:
          slurm_mem: 20GB

      - label: ":rocket: Slabplanet: default (unthreaded) - flame graph diff"
        command: "julia --color=yes --project=perf perf/flame_diff.jl --run_name 1 --job_id perf_diff_default_modular_unthreaded"
        artifact_paths: "perf/output/perf_diff_default_modular_unthreaded/*"
        agents:
          slurm_mem: 20GB

      # < end Drivers for release

      # - label: "Unit tests"
      #   command: "julia --color=yes --project=test test/runtests.jl"
      #   artifact_paths: "test/*"

      - label: "Moist earth with slab surface - default: monin gray no_sponge idealinsol freq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 4 --precip_model 0M --run_name default_mono --job_id default_mono"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/default_mono_artifacts/total_energy*.png"
        agents:
          slurm_mem: 20GB

      - label: "Moist earth with slab surface - default: monin gray no_sponge idealinsol freq_dt_cpl - bucket using BulkAlbedoFunction"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 4 --precip_model 0M --albedo_from_file false --run_name default_albedo_prescribed --job_id default_albedo_from_file"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/default_albedo_from_file_artifacts/total_energy*.png"
        agents:
          slurm_mem: 20GB

      - label: "Moist earth with slab surface - notmono: monin gray no_sponge idealinsol freq_dt_cpl notmono"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface false --h_elem 4 --precip_model 0M --run_name default_notmono --job_id default_notmono"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/default_notmono_artifacts/total_energy*.png"
        agents:
          slurm_mem: 20GB

      # Note: this test fails when run with the more realistic albedo from file
      - label: "Moist earth with slab surface - target: monin allsky sponge realinsol infreq_dt_cpl - bucket using BulkAlbedoFunction"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64  --run_name target_params_in_slab --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 3600 --dt 200secs --dt_rad 6hours --idealized_insolation false --mono_surface true --h_elem 6 --precip_model 0M --albedo_from_file false --job_id target_params_in_slab" # idealized albedo breaks
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/target_params_in_slab_artifacts/total_energy*.png"
        agents:
          slurm_mem: 20GB

      # - label: "Moist earth with slab surface - test: monin allsky sponge idealinsol infreq_dt_cpl"
        # command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 21600 --dt 200secs --dt_rad 6hours --mono_surface true --h_elem 4 --precip_model 0M --run_name target_params_in_slab_test1 --job_id target_params_in_slab_test1" # Unconverged SF (reproduced locally); works with 200s dt_cpl
        # artifact_paths: "experiments/AMIP/modular/output/slabplanet/target_params_in_slab_test1_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - test: bulk allsky sponge realinsol infreq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 3600 --dt 200secs --dt_rad 6hours --idealized_insolation false --mono_surface true --h_elem 6 --precip_model 0M --run_name target_params_in_slab_test2 --job_id target_params_in_slab_test2"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/target_params_in_slab_test2_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - test: monin gray sponge realinsol infreq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 3600 --dt 200secs --dt_rad 6hours --idealized_insolation false --mono_surface true --h_elem 6 --precip_model 0M --run_name target_params_in_slab_test3 --job_id target_params_in_slab_test3"
        artifact_paths: "experiments/AMIP/modular/output/slabplanet/target_params_in_slab_test3_artifacts/total_energy*.png"
        agents:
          slurm_mem: 20GB

      # breaking:
      # - label: "Moist earth with slab surface - monin allsky no_sponge idealinsol infreq_dt_cpl"
      #   command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge false --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 21600 --dt 200secs --dt_rad 6hours --idealized_insolation true --mono_surface true --h_elem 4 --precip_model 0M --run_name target_params_in_slab1"
      #   artifact_paths: "experiments/AMIP/modular/output/slabplanet/target_params_in_slab1_artifacts/total_energy*.png"

      - label: "AMIP - modular Float64"
        key: "modular_amip"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name coarse_single_modular --FLOAT_TYPE Float64 --coupled true  --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --energy_check false --mode_name amip --anim true --t_end 32days --dt_save_to_sol 1days --dt_cpl 400 --dt 400secs --mono_surface false --h_elem 6 --dt_save_restart 10days --precip_model 0M --job_id coarse_single_modular"
        artifact_paths: "experiments/AMIP/modular/output/amip/coarse_single_modular_artifacts/*"
        env:
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: "AMIP - modular, Float32 test" # Issue #271
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name coarse_single_modular_ft32 --FLOAT_TYPE Float64 --coupled true  --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --energy_check false --mode_name amip --anim true --t_end 10days --dt_save_to_sol 100days --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 6 --dt_save_restart 10days --precip_model 0M --job_id coarse_single_modular_ft32"
        artifact_paths: "experiments/AMIP/modular/output/amip/coarse_single_modular_ft32_artifacts/*"
        agents:
          slurm_ntasks: 1
          slurm_mem: 20GB

      - label: "sea_breeze"
        command: "julia --color=yes --project=experiments/ClimaCore/sea_breeze experiments/ClimaCore/sea_breeze/run.jl"
        artifact_paths: "sea_breeze/"

      - label: "MPI AMIP"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --energy_check false --mode_name amip --anim true --t_end 32days --dt_save_to_sol 1days --dt_cpl 400 --dt 400secs --mono_surface false --h_elem 6 --dt_save_restart 5days --precip_model 0M --run_name coarse_mpi_n2 --job_id coarse_mpi_n2"
        artifact_paths: "experiments/AMIP/modular/output/amip/coarse_mpi_n2_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 2
          slurm_mem: 20GB

      # short high-res performance test
      - label: "Unthreaded AMIP FINE" # also reported by longruns with a flame graph
        key: "unthreaded_amip_fine"
        command: "julia --color=yes --project=experiments/AMIP/modular/ experiments/AMIP/modular/coupler_driver_modular.jl --run_name target_amip_n1_shortrun --FLOAT_TYPE Float64 --coupled true --surface_setup PrescribedSurface --moist equil --vert_diff true --rad gray --z_elem 50 --dz_top 3000 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --z_stretch false --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --dt_cpl 150 --dt 150secs --dt_rad 1hours --FLOAT_TYPE Float64 --energy_check false --mode_name amip --t_end 0.01days --dt_save_to_sol 1days --mono_surface false --precip_model 0M --job_id target_amip_n1_shortrun"
        artifact_paths: "experiments/AMIP/modular/output/amip/target_amip_n1_shortrun_artifacts/*"
        env:
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_mem: 20GB

      # flame graphs + allocation tests

      - label: ":rocket: flame graph and allocation tests: perf_coarse_single_modular"
        command: "julia --color=yes --project=perf perf/flame.jl --run_name 2 --job_id perf_coarse_single_modular"
        artifact_paths: "perf/output/perf_coarse_single_modular/*"
        agents:
          slurm_mem: 20GB

      - label: ":rocket: performance: flame graph diff: perf_diff_coarse_single_modular"
        command: "julia --color=yes --project=perf perf/flame_diff.jl --run_name 2 --job_id perf_diff_coarse_single_modular"
        artifact_paths: "perf/output/perf_diff_coarse_single_modular/*"
        agents:
          slurm_mem: 20GB

      - wait

      # plot job performance history
      - label: ":chart_with_downwards_trend: build history"
        command:
          - build_history staging # name of branch to plot
        artifact_paths:
          - "build_history.html"
