agents:
  queue: central
  slurm_time: 24:00:00
  modules: julia/1.10.0 cuda/12.2 ucx/1.14.1_cuda-12.2 openmpi/4.1.5_cuda-12.2 nsight-systems/2023.3.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_CUDA_MEMORY_POOL: none
  JULIA_MPI_HAS_CUDA: "true"
  MPITRAMPOLINE_LIB: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/lib64/libmpiwrapper.so"
  MPITRAMPOLINE_MPIEXEC: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/bin/mpiwrapperexec"

  CONFIG_PATH: "config/model_configs"
  PERF_CONFIG_PATH: "config/perf_configs"
  MPI_CONFIG_PATH: "config/mpi_configs"

timeout_in_minutes: 240

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - |
        if [ -n "$$CLEAR_DEPOT" ]; then
          echo "--- Clearing depot"
          rm -rf ${JULIA_DEPOT_PATH}
        fi

      # Local MPIPreferences take precedence over the one set by JuliaProject.toml,
      # so we make sure that we remove them to use MPITrampoline.
      #
      # TODO: This can be removed once all the branches that use MPIPreferences
      # are deleted

      - echo "--- Instantiate AMIP env"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 12
      slurm_gpus: 1
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - label: "MPI AMIP"
    command: "srun julia --color=yes --project=experiments/AMIP/ experiments/AMIP/coupler_driver.jl --config_file $CONFIG_PATH/coarse_mpi_n2.yml"
    artifact_paths: "experiments/AMIP/output/amip/coarse_mpi_n2_artifacts/*"
    timeout_in_minutes: 240
    env:
      CLIMACORE_DISTRIBUTED: "MPI"
    agents:
      slurm_ntasks: 2
      slurm_mem: 16GB

