env:
  JULIA_VERSION: "1.8.2"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1
  slurm_time: 24:00:00

timeout_in_minutes: 1440

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      # - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate package env"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate sea breeze env"
      - "julia --project=experiments/ClimaCore/sea_breeze -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/ClimaCore/sea_breeze -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/ClimaCore/sea_breeze -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate amip env"
      - "julia --project=experiments/AMIP/moist_mpi_earth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments/AMIP/moist_mpi_earth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=experiments/AMIP/moist_mpi_earth/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf env"
      - "julia --project=perf/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test env"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=artifacts -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=artifacts -e 'using Pkg; Pkg.status()'"
      - "julia --project=artifacts artifacts/download_artifacts.jl"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Unit Tests"
    steps:
      - label: "MPI Regridder unit tests"
        key: "regridder_mpi_tests"
        command: "mpiexec julia --color=yes --project=test/ test/mpi_tests/regridder_mpi_tests.jl --run_name regridder_mpi"
        timeout_in_minutes: 5
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          config: cpu
          queue: central
          slurm_nodes: 3
          slurm_tasks_per_node: 1

      - label: "MPI BCReader unit tests"
        key: "bcreader_mpi_tests"
        command: "mpiexec julia --color=yes --project=test/ test/mpi_tests/bcreader_mpi_tests.jl --run_name bcreader_mpi"
        timeout_in_minutes: 20
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          config: cpu
          queue: central
          slurm_nodes: 3
          slurm_tasks_per_node: 1

      - label: "Perf flame graph diff tests"
        command: "julia --color=yes --project=perf/ perf/flame_test.jl --run_name flame_test"
        timeout_in_minutes: 5
        agents:
          config: cpu
          queue: central
          slurm_nodes: 3
          slurm_tasks_per_node: 1


  - group: "Integration Tests"
    steps:

      # - label: "Unit tests"
      #   command: "julia --color=yes --project=test test/runtests.jl"
      #   artifact_paths: "test/*"

      - label: "Moist earth with slab surface - default: bulk gray no_sponge idealinsol freq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 4 --precip_model 0M --run_name default_mono"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/default_mono_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - default: bulk gray no_sponge idealinsol freq_dt_cpl - bucket using BulkAlbedoFunction"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface true --h_elem 4 --precip_model 0M --albedo_from_file false --run_name default_albedo_prescribed"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/default_albedo_from_file_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - notmono: bulk gray no_sponge idealinsol freq_dt_cpl notmono"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface false --h_elem 4 --precip_model 0M --run_name default_notmono"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/default_notmono_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - notmono + modular: bulk gray no_sponge idealinsol freq_dt_cpl"
        key: "modular_slabplanet"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver_modular.jl --run_name default_modular --enable_threading true --coupled true --surface_scheme bulk  --moist equil --vert_diff true --rad gray --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 200 --dt 200secs --mono_surface false --h_elem 4 --precip_model 0M"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/default_modular_artifacts/total_energy*.png"
        env:
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 1
          slurm_mem_per_cpu: 16G

      # Note: this test fails when run with the more realistic albedo from file
      - label: "Moist earth with slab surface - target: monin allsky sponge realinsol infreq_dt_cpl - bucket using BulkAlbedoFunction"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 3600 --dt 200secs --dt_rad 6hours --idealized_insolation false --mono_surface true --h_elem 6 --precip_model 0M --albedo_from_file false --run_name target_params_in_slab"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/target_params_in_slab_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - test: monin allsky sponge idealinsol infreq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 21600 --dt 200secs --dt_rad 6hours --idealized_insolation true --mono_surface true --h_elem 4 --precip_model 0M --run_name target_params_in_slab_test1"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/target_params_in_slab_test1_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - test: bulk allsky sponge realinsol infreq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme bulk --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 3600 --dt 200secs --dt_rad 6hours --idealized_insolation false --mono_surface true --h_elem 6 --precip_model 0M --run_name target_params_in_slab_test2"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/target_params_in_slab_test2_artifacts/total_energy*.png"

      - label: "Moist earth with slab surface - test: monin gray sponge realinsol infreq_dt_cpl"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad gray --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 3600 --dt 200secs --dt_rad 6hours --idealized_insolation false --mono_surface true --h_elem 6 --precip_model 0M --run_name target_params_in_slab_test3"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/target_params_in_slab_test3_artifacts/total_energy*.png"

      # breaking:
      # - label: "Moist earth with slab surface - monin allsky no_sponge idealinsol infreq_dt_cpl"
      #   command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad allskywithclear --rayleigh_sponge false --energy_check true --mode_name slabplanet --t_end 10days --dt_save_to_sol 3600secs --dt_cpl 21600 --dt 200secs --dt_rad 6hours --idealized_insolation true --mono_surface true --h_elem 4 --precip_model 0M --run_name target_params_in_slab1"
      #   artifact_paths: "experiments/AMIP/moist_mpi_earth/output/slabplanet/target_params_in_slab1_artifacts/total_energy*.png"

      - label: "AMIP"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --enable_threading true --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad gray --energy_check false --mode_name amip --anim true --t_end 32days --dt_save_to_sol 1days --dt_cpl 400 --dt 400secs --mono_surface false --h_elem 6 --dt_save_restart 10days --precip_model 0M --run_name coarse_single"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/amip/coarse_single_artifacts/*"

      - label: "AMIP - modular"
        key: "modular_amip"
        command: "julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver_modular.jl --run_name coarse_single_modular --enable_threading true --coupled true  --surface_scheme bulk --moist equil --vert_diff true --rad gray --energy_check false --mode_name amip --anim true --t_end 32days --dt_save_to_sol 1days --dt_cpl 400 --dt 400secs --mono_surface false --h_elem 6 --dt_save_restart 10days --precip_model 0M"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/amip/coarse_single_modular_artifacts/*"
        env:
          FLAME_PLOT: ""
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 1
          slurm_mem_per_cpu: 16G

      - label: "sea_breeze"
        command: "julia --color=yes --project=experiments/ClimaCore/sea_breeze experiments/ClimaCore/sea_breeze/run.jl"
        artifact_paths: "sea_breeze/"

      - label: "MPI AMIP"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad gray --energy_check false --mode_name amip --anim true --t_end 32days --dt_save_to_sol 1days --dt_cpl 400 --dt 400secs --mono_surface false --h_elem 6 --dt_save_restart 5days --precip_model 0M --run_name coarse_mpi_n2"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/amip/coarse_mpi_n2_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
        agents:
          slurm_ntasks: 2

      - label: "MPI AMIP FINE"
        key: "mpi_amip_fine"
        command: "mpiexec julia --color=yes --project=experiments/AMIP/moist_mpi_earth/ experiments/AMIP/moist_mpi_earth/coupler_driver.jl --run_name target_amip_n32_shortrun --coupled true --surface_scheme monin_obukhov --moist equil --vert_diff true --rad allskywithclear --z_elem 50 --dz_top 3000 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --rayleigh_sponge true --alpha_rayleigh_uh 0 --alpha_rayleigh_w 10 --dt_cpl 150 --dt 150secs --dt_rad 1hours --idealized_insolation false --FLOAT_TYPE Float64 --energy_check false --mode_name amip --t_end 5days --dt_save_to_sol 10days --mono_surface false --precip_model 0M"
        artifact_paths: "experiments/AMIP/moist_mpi_earth/output/amip/target_amip_n32_shortrun_artifacts/*"
        env:
          CLIMACORE_DISTRIBUTED: "MPI"
          BUILD_HISTORY_HANDLE: ""
        agents:
          slurm_ntasks: 32
          slurm_mem_per_cpu: 16G

      # performance tests
      - label: ":rocket: flame graph and allocation tests: perf_default_modular"
        command: "julia --color=yes --project=perf perf/flame.jl --run_name 1"
        artifact_paths: "perf/output/perf_default_modular/*"
        agents:
          slurm_mem: 20GB

      - label: ":rocket: flame graph and allocation tests: perf_coarse_single_modular"
        command: "julia --color=yes --project=perf perf/flame.jl --run_name 2"
        artifact_paths: "perf/output/perf_coarse_single_modular/*"
        agents:
          slurm_mem: 20GB

      - label: ":rocket: flame graph and allocation tests: perf_target_amip_n32_shortrun"
        command: "julia --color=yes --project=perf perf/flame.jl --run_name 3"
        artifact_paths: "perf/output/perf_target_amip_n32_shortrun/*"
        agents:
          slurm_mem: 20GB

      - label: ":rocket: performance: flame graph diff: perf_default_modular"
        command: "julia --color=yes --project=perf perf/flame_diff.jl --run_name 1"
        artifact_paths: "perf/output/perf_diff_default_modular/*"
        agents:
          slurm_mem: 20GB

      - label: ":rocket: performance: flame graph diff: perf_coarse_single_modular"
        command: "julia --color=yes --project=perf perf/flame_diff.jl --run_name 2"
        artifact_paths: "perf/output/perf_diff_coarse_single_modular/*"
        agents:
          slurm_mem: 20GB

      - wait

      # plot job performance history
      - label: ":chart_with_downwards_trend: build history"
        command:
          - build_history staging # name of branch to plot
        artifact_paths:
          - "build_history.html"

