FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
anim: false
atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
dt: "120secs"
dt_cpl: 120
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
energy_check: false
hourly_checkpoint: true
hourly_checkpoint_dt: 720
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "1098days"
topo_smoothing: true
topography: "Earth"
coupler_toml_file: "toml/amip.toml"
turb_flux_partition: "CombinedStateFluxesMOST"
aerosol_radiation: false
# diagnostics:
#   - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr]
#     period: 1days
#   - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke, lmix]
#     period: 1days
#   - short_name: [rsdt, rsut, rlut, rsds, rsus, rlds, rlus, hfes]
#     period: 1days
