FLOAT_TYPE: "Float32"
aerosol_radiation: false
albedo_model: "CouplerAlbedo"
anim: false
atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
dt: "120secs"
dt_cpl: 120
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
energy_check: false
hourly_checkpoint: true
hourly_checkpoint_dt: 720
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: true
prescribed_aerosols: []
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "1080days"
topo_smoothing: true
topography: "Earth"
coupler_toml_file: "toml/amip.toml"
turb_flux_partition: "CombinedStateFluxesMOST"
