[zd_rayleigh]
value = 35000.0
type = "float"

[alpha_rayleigh_uh]
alias = "alpha_rayleigh_uh"
value = 0.0
type = "float"

[precipitation_timescale]
value = 600
type = "float"

[min_area_limiter_scale]
value = 0
type = "float"

[max_area_limiter_scale]
value = 0
type = "float"