apply_limiter: false
dt: "400secs"
dt_cpl: 400
dt_save_restart: "10days"
dt_save_to_sol: "1days"
energy_check: false
h_elem: 6
hourly_checkpoint: true
hourly_checkpoint_dt: 1
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "allskywithclear"
t_end: "800secs"
vert_diff: "true"
