FLOAT_TYPE: "Float32"
anim: true
apply_limiter: false
dt: "400secs"
dt_cpl: 400
dt_save_to_sol: "100days"
energy_check: false
h_elem: 6
mode_name: "amip"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "allskywithclear"
t_end: "10days"
vert_diff: "true"
