apply_limiter: false
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "3600secs"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "gray"
run_name: "default_notmono"
t_end: "10days"
vert_diff: "true"
