FLOAT_TYPE: "Float32"
alpha_rayleigh_uh: 0
alpha_rayleigh_w: 10
apply_limiter: false
dt: "120secs"
dt_cloud_fraction: 1hours
dt_cpl: 120
dt_rad: "1hours"
dt_save_state_to_disk: "Inf"
dt_save_to_sol: "Inf"
dz_bottom: 30.0
dz_top: 3000.0
h_elem: 30
land_albedo_type: "map_temporal"
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "allskywithclear"
surface_setup: DefaultMoninObukhov
t_end: "12hours"
use_coupler_diagnostics: false
vert_diff: "true"
z_elem: 63
z_max: 55000.0
