anim: true
apply_limiter: false
coupler_output_dir: "experiments/ClimaEarth/output"
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "10days"
energy_check: true
evolving_ocean: true
h_elem: 4
land_albedo_type: "function"
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "20days"
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "true"
