anim: true
apply_limiter: false
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "9days"
energy_check: true
h_elem: 4
job_id: "slabplanet_default"
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
run_name: "slabplanet_default"
t_end: "10days"
vert_diff: "true"
output_default_diagnostics: false
diagnostics:
 - short_name: [mse, lr, ediff, hfes, evspsbl, ts]
   period: 1days

