FLOAT_TYPE: "Float32"
anim: true
apply_limiter: false
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "9days"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
run_name: "slabplanet_ft32"
t_end: "10days"
vert_diff: "true"
