anim: true
apply_limiter: false
conservation_softfail: true
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "9days"
energy_check: true
h_elem: 6
job_id: "slabplanet_eisenman"
mode_name: "slabplanet_eisenman"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
run_name: "slabplanet_eisenman"
surface_setup: "PrescribedSurface"
t_end: "2days"
vert_diff: "true"
