apply_limiter: false
dt: "200secs"
dt_cpl: 200
dt_save_to_sol: "3600secs"
energy_check: true
h_elem: 30
land_albedo_type: "map_temporal"
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
t_end: "10days"
vert_diff: "true"
