FLOAT_TYPE: "Float32"
approximate_linear_solve_iters: 2
dt: 120secs
dt_cloud_fraction: 1hours
dt_rad: 1hours
dt_save_state_to_disk: "Inf"
dt_save_to_sol: "Inf"
dz_bottom: 30.0
dz_top: 3000.0
h_elem: 30
insolation: "timevarying"
implicit_diffusion: true
moist: equil
output_default_diagnostics: false
precip_model: 0M
rad: allskywithclear
surface_setup: DefaultMoninObukhov
t_end: 12hours
turb_flux_partition: "CombinedStateFluxesMOST"
vert_diff: "FriersonDiffusion"
z_elem: 63
z_max: 55000.0
