anim: false
apply_limiter: false
atmos_config_file: "config/gpu_configs/gpu_aquaplanet_chap_4process.yml"
dt: "100secs"
dt_cloud_fraction: "1hours"
dt_cpl: 100
dt_rad: "1hours"
dt_save_state_to_disk: "Inf"
dt_save_to_sol: "Inf"
energy_check: false
evolving_ocean: false
hourly_checkpoint: false
job_id: "gpu_amip_chap_4process"
land_albedo_type: "map_static"
mode_name: "amip"
mono_surface: false
run_name: "gpu_amip_chap_4process"
start_date: "19790301"
surface_setup: "PrescribedSurface"
t_end: "1days"
turb_flux_partition: "CombinedStateFluxes"
vert_diff: "true"
