name: Unit Tests

on:
  pull_request:
  
  push:
    branches: [ main ]

jobs:
  test-os:
    timeout-minutes: 120
    strategy:
      matrix:
        julia-version: [1.5]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup a filter and only run if src/ test/ folder content changes
      # or project depedencies
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            run_test:
              - 'src/**'
              - 'test/**'
              - 'Project.toml'
              - 'Manifest.toml'

      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        if: steps.filter.outputs.run_test == 'true'
        with:
          version: ${{ matrix.julia-version }}

      # https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484
      - name: Cache artifacts
        uses: actions/cache@v2
        if: steps.filter.outputs.run_test == 'true'
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
            
      - uses: julia-actions/julia-buildpkg@master
        if: steps.filter.outputs.run_test == 'true'
        
      - uses: julia-actions/julia-runtest@master
        if: steps.filter.outputs.run_test == 'true'
